version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: CleanArchitecture-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Your_password123!}
      - POSTGRES_DB=CleanArchitectureDb
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - CleanArchitecture-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgresql-data:

networks:
  CleanArchitecture-network:
    driver: bridge