version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: CleanArchitecture-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - CleanArchitecture-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
//-:cnd:noEmit
#if (UseRedisAuth)
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-Your_password123!}
#else
    command: redis-server --appendonly yes
#endif
//+:cnd:noEmit

volumes:
  redis-data:

networks:
  CleanArchitecture-network:
    driver: bridge