version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: CleanArchitecture-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-Your_password123!}
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - CleanArchitecture-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  rabbitmq-data:

networks:
  CleanArchitecture-network:
    driver: bridge